<?php
/**
 * @file
 * This is an example describing how a module can display data in a sortable table
 *
 * See:
 * @link http://drupal.org/node/508796 Extenders @endlink
 * @link http://drupal.org/developing/api/database Database API @endlink
 */


/**
 * Implements hook_help().
 *
 * Show a bit of information about this module on the example page
 */
function tablesort_example_help($path, $arg) {
  switch ($path) {
    case 'examples/tablesort_example':
      return '<p>' . t('The layout here is a themed as a table that is sortable by clicking the header name.') . '</p>';
    case 'admin/help#tablesort_example':
      // This is also viewable from a 'Help' link on the Module page
      return t('This is simple help text for the table sort example');
  }
}

/**
 * Implements hook_menu().
 */
function tablesort_example_menu() {
  $items['examples/tablesort_example'] = array(
    'title'           => 'TableSort example',
    'description'     => 'Show a page with a sortable table',
    'page callback'   => 'tablesort_example_page',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Build the table render array.
 *
 * @return
 *   A render array set for theming by theme_table().
 */
function tablesort_example_page() {
  $build = 'Hello from tablesort_example_page callback';
  return $build;
}
